version: '3'
services:
    nginx:
        container_name: plant_and_pouss_nginx
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./PlantAndPouss:/var/www/html
        ports:
            - 80:80
        restart: always
        networks:
            - plant_and_pouss_net
        depends_on:
            - php
            - db
    php:
        container_name: plant_and_pouss_php
        build: .docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./PlantAndPouss:/var/www/html
        networks:
            - plant_and_pouss_net
    db:
        container_name: plant_and_pouss_db
        image: postgres:10.1
        restart: always
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /data/postgres
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
            - postgres:/data/postgres
        ports:
            - 5432:5432
        networks:
            - plant_and_pouss_net
    pgadmin:
        container_name: plant_and_pouss_pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        restart: unless-stopped
        networks:
            - plant_and_pouss_net

networks:
    plant_and_pouss_net:

volumes:
    postgres:
    pgadmin: